### ISSUE TITLE
error: ‘void clang::Preprocessor::EnterTokenStream(const clang::Token*, unsigned int, bool, bool)’ is private

### ISSUE THREAD

**Issue by XiaZhouZero** [cwg2205195/ExtClangPragma#1]
Hi, cwg2205195, very nice tutorial!
I tried your code on obfuscator(llvm4.0) but I encountered this problem below:
```
In file included from /home/neo/ollvm/obfuscator/tools/clang/include/clang/Parse/Parser.h:22:0,
                 from /home/neo/ollvm/obfuscator/tools/clang/lib/Parse/RAIIObjectsForParser.h:19,
                 from /home/neo/ollvm/obfuscator/tools/clang/lib/Parse/ParseStmt.cpp:15:
/home/neo/ollvm/obfuscator/tools/clang/include/clang/Lex/Preprocessor.h: In member function ‘clang::StmtResult clang::Parser::HandlePragmaMyAnnotate(bool)’:
/home/neo/ollvm/obfuscator/tools/clang/include/clang/Lex/Preprocessor.h:1044:8: error: ‘void clang::Preprocessor::EnterTokenStream(const clang::Token*, unsigned int, bool, bool)’ is private
   void EnterTokenStream(const Token *Toks, unsigned NumToks,
        ^
/home/neo/ollvm/obfuscator/tools/clang/lib/Parse/ParseStmt.cpp:194:76: error: within this context
     PP.EnterTokenStream(tokenArray, (unsigned)TokenList.size(), false, true);
```
Then I made `EnterTokenStream(const clang::Token*, unsigned int, bool, bool)` a public one and finally succeeded.
Can you tell me which version of LLVM that you used or do you have any advice on this problem?
Thanks a lot!

**Comment by cwg2205195** [comment]
I used LLVM 4.0 for this work . I forgot to mentation that I changed `EnterTokenStream(const clang::Token*, unsigned int, bool, bool)`  into a public method . Sorry about that .

**Comment by XiaZhouZero** [comment]
> I used LLVM 4.0 for this work . I forgot to mentation that I changed `EnterTokenStream(const clang::Token*, unsigned int, bool, bool)` into a public method . Sorry about that .

OK, I see. Thanks for your reply!
